name: flask-profiler CI tests

on:
  push:

jobs:
  build-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
    - run: nix flake check --print-build-logs

